// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image3":
            case "Jag2":return img`
................................
................................
...........fffffffffffffff......
...fffffffffaaaaacacfffffff.....
..ffaaccffffffaaaaaaaaccfcfff...
.fffaaaaaaaaaaccfcccaaaaaaacff..
.fffaaaacccccffcaaaccffffcaacff.
.fffaaaacaaafffaaaacaccafaaaacf.
.fffaaccacaafffaaaacaaaafaacaaf.
.fffcaacacfccfaaaaaaaaaffaaccaf.
.ffffcaaafffccaaaaaaaaafaaaacaf.
.ffcfffcaffffccaaaaafaafaaaaaaf.
.ffacfffffffcccaaafffaafaacaaaf.
.ffaaffffffffcfaaaafaaafafaacaf.
..fcacffcccccffaaaaafaafffaaacf.
..ffaaafcccacfcccaaafaffffaaacf.
...fcaacfccacfcacaaffffffaaaaf..
...ffaaafffffcacacafffffaaaaaf..
...ffcaacfffffcffffffffaaaaccf..
...ffaaaaacfffccffffffaaaaaacf..
...ffaaaaaccffcaaaaffaaaaaacf...
....facacccffffaaaafcaaaaaaff...
....fcfccfff..fccccfcaaaaccf....
.....ffff.f....fffffaaaaacff....
..................fcaaaaaaff....
.................ffaaaaaaacf....
.................fcaaaaaaaaf....
.................fcafaafafff....
.................ffffaafafff....
..................fffcffcfff....
....................ffff........
................................
`;
            case "image2":
            case "Jag1":return img`
................................
................................
......fffffffffffffff...........
.....fffffffcacaaaaaccfffffff...
...fffcfccaaaaaaaacccfffccaaff..
..ffcaaaaaaaffffffaaaaaaaaaafff.
.ffcaacffffffaaaffffffffaaaafff.
.fcaaaafaccafaaaafffaaafaaaafff.
.faacaafaaaafaaaafffaacaccaafff.
.faccaaffaaaaaaaaafccfcacaacfff.
.facaaaafaaaaaaaaaccfffaaacffff.
.faaaaaafaafaaaaaccffffacfffcff.
.faaacaafaafffaaacccfffffffcaff.
.facaafafaaafaaaafcffffffffaaff.
.fcaaafffaafaaaaaffcccccffcacf..
.fcaaaffffafaaacccfcacccfaaaff..
..faaaaffffffaacacfcaccfcaacf...
..faaaaafffffacacacfffffaaaff...
..fccaaaaffffffffcfffffcaacff...
..fcaaaaaaffffffccfffcaaaaacf...
...fcaaaaaaffaaaacffccaaaaacf...
...ffaaaaaacfaaaaffffcccacac....
....fccaaaacfccccf..fffccfcf....
....ffcaaaaafffff....f.ffff.....
....ffaaaaaacf..................
....fcaaaaaaaff.................
....faaaaaaaacf.................
....fffafaafacf.................
....fffafaaffff.................
....ffffffcfff..................
........ffff....................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim3":return [img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
